# The name of the frame for the base link of the robot. 
robot_base_frame: base_link

# Specifies the delay in transform (tf) data that is tolerable in seconds. For example, 
# a transform being 0.2 seconds out-of-date may be tolerable, but a transform being 8 seconds 
# out of date is not. In that case, the navigation stack will stop the robot. 
transform_tolerance: 0.5

# The frequency in Hz for the map to be updated. 
update_frequency: 5.0

# The frequency in Hz for the map to be publish display information. 
publish_frequency: 5.0

# The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters.
# This means that the robot will only update its map with information about obstacles that are within 5.0 meters of the base
obstacle_range: 5.0 # 1.0

# The default range in meters at which to raytrace out obstacles from the map using sensor data.
raytrace_range: 3.0 # 3.0

# If true the full costmap is published to "~<name>/costmap" every update. 
# If false only the part of the costmap that has changed is published on the "~<name>/costmap_updates" topic. 
always_send_full_costmap: false

# The footprint of the robot specified in the robot_base_frame coordinate 
# frame as a list in the format: [ [x1, y1], [x2, y2], ...., [xn, yn] ]. 
# The footprint specification assumes the center point of the robot is at 
# (0.0, 0.0) in the robot_base_frame and that the points are specified in meters, 
# both clockwise and counter-clockwise orderings of points are supported. 
footprint: [[-0.15, -0.3], [-0.15, 0.1], [0.15, 0.1], [0.15, -0.3]]

inflation_radius: 1.75

cost_scaling_factor: 2.58

