# map_type: costmap

# The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters.
# This means that the robot will only update its map with information about obstacles that are within 5.0 meters of the base
obstacle_range: 5.0 # 1.0

# The default range in meters at which to raytrace out obstacles from the map using sensor data.
raytrace_range: 3.0 # 3.0

# transform_tolerance: 0.2 # 0.0

# The footprint of the robot specified in the robot_base_frame coordinate 
# frame as a list in the format: [ [x1, y1], [x2, y2], ...., [xn, yn] ]. 
# The footprint specification assumes the center point of the robot is at 
# (0.0, 0.0) in the robot_base_frame and that the points are specified in meters, 
# both clockwise and counter-clockwise orderings of points are supported. 
footprint: [[-0.15, -0.3], [-0.15, 0.1], [0.15, 0.1], [0.15, -0.3]]
# robot_radius: 0.4 # 0.0
inflation_radius: 0.3 # 0.0
# cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
